config/routes.rb
Rails.application.routes.draw do
  resources :merits
  resources :batches do
    member do
      get 'random/:group_count' => 'batches#random'
    end

    resources :divisions
  end

  resources :divisions, only: [] do
    resources :challenges

    member do
      get 'teams'
      get 'captains', to: 'divisions#get_captians'
    end
  end

  resources :groups, only: [:show] do
    member do
      post 'award'
    end
  end

  get ':batch_num/today' => 'divisions#today'
  get 'today' => 'divisions#today'

  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/division.rb
class Division < ApplicationRecord
  attr_accessor :number_of_groups
  belongs_to :batch
  has_many :groups
  has_many :challenges

  def latest_challenge
    challenges.last
  end

  def self.today
    now = Time.zone.now
    self.where(:created_at => (now.beginning_of_day..now.end_of_day)).first
  end

  def groups_sorted_by_student_count
    groups.sort_by{|g| g.students.count }
  end

  def is_today
    created_at.to_date == Date.current
  end

  after_save :build_groups, :if => Proc.new { |model| model.number_of_groups }

  def generate_group_captains!
    groups.each do |group|
      group.randomize_captain!
    end
  end

  private

  def build_groups
    groups.destroy_all
    student_groups = batch.students.shuffle.in_groups(self.number_of_groups.to_i, false).to_a

    student_groups.each_with_index do |student_group, index|
      group = Group.create(division: self, name: Group.random_name)
      student_group.each do |student|
        Groupship.create(student: student, group: group)
      end
    end
  end
end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:today]
  before_action :set_division, only: [:show, :edit, :update, :destroy, :random, :get_captians]
  before_action :set_batch

  def today
    @division = Division.today

    if !@batch
      redirect_to new_batch_path
    elsif @division
      # @timer = @challenge.minutes_to_string
      @timer = '0:10'
      @challenge = @division.latest_challenge || Challenge.new
      render :show
    else
      @division = Division.new
      render :new
    end
  end

  def get_captians
    @division.generate_group_captains!
    @groups = @division.groups
  end

  def teams
    @division = Division.today
  end

  def index
    @divisiones = Division.all
  end

  def show
    @challenge = Challenge.new
  end

  def new
    @division = Division.new
  end

  def edit
  end

  def create
    @division = Division.new(division_params)
    @division.batch = @batch

    if @division.save
      if @division.is_today
        redirect_to today_path, notice: 'division was successfully created.'
      else
        redirect_to division_path(@batch, @division), notice: 'division was successfully created.'
      end
    else
      render :new
    end
  end

  def update
    if @division.update(division_params)
      if @division.is_today
        redirect_to today_path, notice: 'division was successfully updated.'
      else
        redirect_to division_path(@batch, @division), notice: 'division was successfully updated.'
      end
    else
      render :edit
    end
  end

  def destroy
    @division.destroy
    redirect_to divisiones_url, notice: 'division was successfully destroyed.'
  end

  private
    def set_division
      @division = Division.find(params[:id])
    end

    def set_batch
      if params[:batch_id]
        @batch = Batch.find_by_id(params[:batch_id])
      elsif params[:batch_num]
        @batch = Batch.find_by_num(params[:batch_id])
      else
        @batch = Batch.find_by_num(97)
      end
    end

    def division_params
      params.require(:division).permit(:number_of_groups)
    end

end

app/views/divisions/_captains.html.erb
<div class="row">
  <% groups.each do |group| %>
    <div class="col-sm-6">
      <div class="captain">
        <h3><%= group.name %></h3>
        <div><%= image_tag group.captain.avatar_url, class: "avatar-large" %></div>
        <div><%= group.captain.name %></div>
      </div>
    </div>
  <% end %>
</div>

app/views/divisions/_form.html.erb
<%= simple_form_for([@batch, @division]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :number_of_groups %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/divisions/edit.html.erb
<h1>New Division</h1>

<%= render 'form', division: @division %>

<%= link_to 'Back', batches_path %>

app/views/divisions/get_captians.js.erb
$("#division-group-list").html("<%= j render 'shared/group_list', groups: @groups %>");
$("#captains-modal").html("<%= j render 'captains', groups: @groups %>");
$("#captains-modal").modal({
  showClose: false,
});

app/views/divisions/new.html.erb
<h1>New Division</h1>

<%= render 'form', division: @division %>

<%= link_to 'Back', batches_path %>

app/views/divisions/show.html.erb
<div class="row">
  <div class="col-md-12">
    <!-- <%= render 'shared/challenge_form', challenge: @challenge %> -->
  </div>
</div>
<div class="row bottom-bumper top-bumper">
  <div class="col-xs-6">
    <%= link_to 'New Team Captains', captains_division_path(@division), remote: true %>
    <% if @division.groups.any?{|group| group.captain } %> - <a href="#captains-modal" rel="modal:open" class="right-bumper">Current Captains</a><% end %>
  </div>
  <div class="col-xs-6 text-right">
    <%= link_to 'Today\'s teams', teams_division_path(@division) %>
  </div>
</div>
<div class="row" id="division-group-list">
  <%= render 'shared/group_list', groups: @division.groups %>
</div>

<%= render 'shared/captians_modal' %>

app/views/divisions/teams.html.erb
<div class="row">
  <% @division.groups_sorted_by_student_count.each do |group| %>
    <div class="col-md-3">
      <%= render 'shared/group_students_card', group: group %>
    </div>
  <% end %>
</div>