config/routes.rb
Rails.application.routes.draw do
  resources :merits
  resources :batches do
    member do
      get 'random/:group_count' => 'batches#random'
    end

    resources :divisions
  end

  resources :divisions, only: [] do
    resources :challenges

    member do
      get 'teams'
      get 'captains', to: 'divisions#get_captians'
    end
  end

  resources :groups, only: [:show] do
    member do
      post 'award'
    end
  end

  get ':batch_num/today' => 'divisions#today'
  get 'today' => 'divisions#today'

  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_captians_modal.html.erb
<div id="captains-modal" style="max-width: inherit; display: none;">
  <% if @division.groups.all?{|group| group.captain } %>
    <%= render 'divisions/captains', groups: @division.groups %>
  <% end %>
</div>

app/views/shared/_challenge_form.html.erb
<%= simple_form_for([@division, @challenge]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :desc %>
    <%= f.input :minutes %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_group_list.html.erb
<ul class="list-group group-list">
  <% groups.each do |group| %>
    <li class="list-group-item team group-<%= group.id %>">
      <%= render 'shared/group_list_row', group: group %>
    </li>
  <% end %>
</ul>

<%= render 'shared/merit_modals', merits: Merit.all %>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      <%= render 'shared/merit_modal_binding', merits: Merit.all %>
    });
  <% end %>
<% end %>

app/views/shared/_group_list_row.html.erb
<div class="row">
  <div class="col-xs-6">
    <h3><%= link_to "+", award_group_path(group), class: "btn btn-success btn-xs", method: :post, remote: :true %> <%= link_to group.name, group_path(group) %><% if group.captain %> - <%= image_tag group.captain.avatar_url, class: "avatar" %><% end %></h3>
    <div>
      <% group.students.each do |student| %>
        <%= image_tag student.avatar_url, class: "avatar" %>
      <% end %>
    </div>
  </div>
  <div class="col-xs-6">
    <div class="score"><%= group.score %></div>
    <div class="badges">
      <% group.merits.each do |merit| %>
        <div class="merit-modal-click" data-modal="#merit-modal-<%= merit.id %>">
        <%= cl_image_tag merit.image, :width=>100, :height=>100, :crop=>"fill", class: "merit-image merit-image-#{ merit.id}" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_group_students_card.html.erb
<h3><%= group.name %></h3>
<!-- <%= link_to "Submit Code" %> -->
<ul class="division-group-card list-group">
  <% group.students.each do |student| %>
    <li class="list-group-item student-card">
      <%= image_tag student.avatar_url, class: "avatar" %>
      <div class="name"><%= student.name %></div>
    </li>
  <% end %>
</ul>

app/views/shared/_merit_modal_binding.html.erb
<% merits.each do |merit| %>
  $(".merit-modal-click").on('click', function() {
    $($(this).data('modal')).modal({
      showClose: true,
    });
    return false;
  });
<% end %>

app/views/shared/_merit_modals.html.erb
<div class="modals">
  <% merits.each do |merit| %>
    <div id="merit-modal-<%= merit.id %>" class="modal">
      <%= render 'shared/merit_summary', merit: merit %>
    </div>
  <% end %>
</div>

app/views/shared/_merit_summary.html.erb
<div class="merit-summary">
  <h1><%= merit.name %></h1>
  <div class="merit-image"><%= cl_image_tag merit.image, :width=>300, :height=>300, :crop=>"fill" %></div>
  <div class="points"><%= merit.points %></div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="badge badge-blue">3</div>
        </div>
      <% end %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_timer.html.erb
<% if @timer %>
  <div id="timer-bar">
    <span id="timer"></span>
    <a id="toggle-timer-video" href="#">toggle video</a>
    <div id="timer-video-wrapper" style="display:none;">
      <iframe id="timer-video" width="300" height="300"
        src="https://www.youtube.com/embed/VBlFHuCzPgY?rel=0">
      </iframe>
    </div>
  </div>

  <% content_for(:after_js) do %>
    <%= javascript_tag do %>
      $(document).ready(function() {

        $('#toggle-timer-video').click(function() {
          $('#timer-video-wrapper').toggle();
        });

        document.getElementById('timer').innerHTML = '<%= @timer %>';
        startTimer();
        playVideo();

        function playVideo() {
          $("#timer-video")[0].src += "&autoplay=1";
        }

        function stopVideo() {
          $("#timer-video")[0].src = $("#timer-video")[0].src.replace("&autoplay=1", '')
        }

        function startTimer() {
          var presentTime = document.getElementById('timer').innerHTML;
          var timeArray = presentTime.split(/[:]+/);
          var m = timeArray[0];
          var s = checkSecond((timeArray[1] - 1));
          if(s==59){m=m-1}

          if(m < 0){
            console.log('timer completed');
            clearTimeout(timeout);
            stopVideo();
          } else {
            document.getElementById('timer').innerHTML =
              m + ":" + s;
            timeout = setTimeout(startTimer, 1000);
          }
        }

        function checkSecond(sec) {
          if (sec < 10 && sec >= 0) {sec = "0" + sec}; // add zero in front of numbers < 10
          if (sec < 0) {sec = "59"};
          console.log('blah seconds ', sec);
          return sec;
        }
      });
    <% end %>
  <% end %>
<% end %>