config/routes.rb
Rails.application.routes.draw do
  resources :merits
  resources :batches do
    member do
      get 'random/:group_count' => 'batches#random'
    end

    resources :divisions
  end

  resources :divisions, only: [] do
    resources :challenges

    member do
      get 'teams'
      get 'captains', to: 'divisions#get_captians'
    end
  end

  resources :groups, only: [:show] do
    member do
      post 'award'
    end
  end

  get ':batch_num/today' => 'divisions#today'
  get 'today' => 'divisions#today'

  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/batch.rb
class Batch < ApplicationRecord
  attr_accessor :classmate_html
  has_many :batchships
  has_many :divisions
  has_many :students, through: :batchships

  validates :num, uniqueness: true
  before_validation :parse_classmate_html, :if => Proc.new { |model| model.classmate_html }

  private
  def parse_classmate_html
    self.batchships.delete_all

    html_doc = Nokogiri::HTML(self.classmate_html)

    student_rows = html_doc.search('#classmates-container tbody > tr')
    student_rows.each do |student_row|
      student_cols = student_row.search('td')

      avatar = student_cols[0].at_css('.img-thumbnail').attribute('src').value
      name = student_cols[1].at_css('strong').text

      student = Student.find_by(name: name)
      if !student
        student = Student.create(name: name, avatar_url: avatar)
      end

      Batchship.create(student: student, batch: self)
    end
  end
end

app/controllers/batches_controller.rb
class BatchesController < ApplicationController
  before_action :set_batch, only: [:show, :edit, :update, :destroy, :random]

  def index
    @batches = Batch.all
  end

  def show
  end

  def new
    @batch = Batch.new
  end

  def edit
  end

  def random
    @groups = @batch.users.to_a.shuffle.each_slice(params[:group_count].to_i).to_a
  end

  def create
    @batch = Batch.new(batch_params)

    if @batch.save
      redirect_to @batch, notice: 'Batch was successfully created.'
    else
      render :new
    end
  end

  def update
    if @batch.update(batch_params)
      redirect_to @batch, notice: 'Batch was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @batch.destroy
    redirect_to batches_url, notice: 'Batch was successfully destroyed.'
  end

  private
    def set_batch
      @batch = Batch.find(params[:id])
    end

    def batch_params
      params.require(:batch).permit(:num, :classmate_html)
    end
end

app/views/batches/_form.html.erb
<%= simple_form_for(@batch) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :num, label: "Number" %>
    <%= f.input :classmate_html, label: "Classmate Page HTML", as: :text %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/batches/edit.html.erb
<h1>Editing Batch</h1>

<%= render 'form', batch: @batch %>

<%= link_to 'Show', @batch %> |
<%= link_to 'Back', batches_path %>

app/views/batches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Batches</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @batches.each do |batch| %>
      <tr>
        <td>Batch <%= batch.num %></td>
        <td><%= link_to 'Show', batch %></td>
        <td><%= link_to 'Edit', edit_batch_path(batch) %></td>
        <td><%= link_to 'Destroy', batch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Batch', new_batch_path %>

app/views/batches/new.html.erb
<h1>New Batch</h1>

<%= simple_form_for(@batch) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :num, label: "Number" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>


<%= link_to 'Back', batches_path %>

app/views/batches/random.html.erb
<div class="container">
  <div class="row">
    <% @groups.each_with_index do |group, index| %>
      <div class="col-md-3">
        <h1>Group <%= index + 1 %></h1>
        <% group.each do |user| %>
          <div><% user.name %> - <%= user.email %></div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/batches/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_batch_path(@batch) %> |
<%= link_to 'Back', batches_path %>