config/routes.rb
Rails.application.routes.draw do
  resources :merits
  resources :batches do
    member do
      get 'random/:group_count' => 'batches#random'
    end

    resources :divisions
  end

  resources :divisions, only: [] do
    resources :challenges

    member do
      get 'teams'
      get 'captains', to: 'divisions#get_captians'
    end
  end

  resources :groups, only: [:show] do
    member do
      post 'award'
    end
  end

  get ':batch_num/today' => 'divisions#today'
  get 'today' => 'divisions#today'

  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/merit.rb
class Merit < ApplicationRecord
  mount_uploader :image, ImageUploader
  before_save :set_points, :if => Proc.new { |model| !model.points }

  def self.random
    offset = rand(self.count)
    self.offset(offset).first
  end

  private
  def set_points
    self.points = rand(1...100)
  end
end

app/controllers/merits_controller.rb
class MeritsController < ApplicationController
  before_action :set_merit, only: [:show, :edit, :update, :destroy]

  # GET /merits
  # GET /merits.json
  def index
    @merits = Merit.all
  end

  # GET /merits/1
  # GET /merits/1.json
  def show
  end

  # GET /merits/new
  def new
    @merit = Merit.new
  end

  # GET /merits/1/edit
  def edit
  end

  # POST /merits
  # POST /merits.json
  def create
    @merit = Merit.new(merit_params)

    respond_to do |format|
      if @merit.save
        format.html { redirect_to @merit, notice: 'Merit was successfully created.' }
        format.json { render :show, status: :created, location: @merit }
      else
        p @merit.errors.messages
        format.html { render :new }
        format.json { render json: @merit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /merits/1
  # PATCH/PUT /merits/1.json
  def update
    respond_to do |format|
      if @merit.update(merit_params)
        format.html { redirect_to @merit, notice: 'Merit was successfully updated.' }
        format.json { render :show, status: :ok, location: @merit }
      else
        format.html { render :edit }
        format.json { render json: @merit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /merits/1
  # DELETE /merits/1.json
  def destroy
    @merit.destroy
    respond_to do |format|
      format.html { redirect_to merits_url, notice: 'Merit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_merit
      @merit = Merit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def merit_params
      params.require(:merit).permit(:group_id, :name, :points, :remote_image_url)
    end
end

app/views/merits/_form.html.erb
<%= simple_form_for(@merit) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :remote_image_url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/merits/edit.html.erb
<h1>Editing Merit</h1>

<%= render 'form', merit: @merit %>

<%= link_to 'Show', @merit %> |
<%= link_to 'Back', merits_path %>

app/views/merits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Merits</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Points</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @merits.each do |merit| %>
      <tr>
        <td><%= merit.name %></td>
        <td><%= merit.points %></td>
        <td><%= merit.image %></td>
        <td><%= link_to 'Show', merit %></td>
        <td><%= link_to 'Edit', edit_merit_path(merit) %></td>
        <td><%= link_to 'Destroy', merit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Merit', new_merit_path %>

app/views/merits/new.html.erb
<h1>New Merit</h1>

<%= render 'form', merit: @merit %>

<%= link_to 'Back', merits_path %>

app/views/merits/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row group-show-merits">
  <div class="col-md-4 col-md-offset-4">
    <%= render 'shared/merit_summary', merit: @merit %>
  </div>
</div>

<%= link_to 'Edit', edit_merit_path(@merit) %> |
<%= link_to 'Back', merits_path %>